name: amlrealtimeai
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - python=3.6
  - scikit-learn=0.19.1
  - tqdm=4.19.5
  - tensorflow=1.10.0
  - pip:
    - --editable ./pythonlib