// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: version.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Aml.Fpga {
  public static partial class VersionService
  {
    static readonly string __ServiceName = "aml.fpga.VersionService";

    static readonly grpc::Marshaller<global::Aml.Fpga.VersionRequest> __Marshaller_VersionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Aml.Fpga.VersionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Aml.Fpga.VersionResponse> __Marshaller_VersionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Aml.Fpga.VersionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Aml.Fpga.VersionRequest, global::Aml.Fpga.VersionResponse> __Method_Version = new grpc::Method<global::Aml.Fpga.VersionRequest, global::Aml.Fpga.VersionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Version",
        __Marshaller_VersionRequest,
        __Marshaller_VersionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Aml.Fpga.VersionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VersionService</summary>
    public abstract partial class VersionServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Aml.Fpga.VersionResponse> Version(global::Aml.Fpga.VersionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VersionService</summary>
    public partial class VersionServiceClient : grpc::ClientBase<VersionServiceClient>
    {
      /// <summary>Creates a new client for VersionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VersionServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VersionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VersionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VersionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VersionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Aml.Fpga.VersionResponse Version(global::Aml.Fpga.VersionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Version(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Aml.Fpga.VersionResponse Version(global::Aml.Fpga.VersionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Version, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Aml.Fpga.VersionResponse> VersionAsync(global::Aml.Fpga.VersionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return VersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Aml.Fpga.VersionResponse> VersionAsync(global::Aml.Fpga.VersionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Version, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override VersionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new VersionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(VersionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Version, serviceImpl.Version).Build();
    }

  }
}
#endregion
